### ISSUE TITLE
Support for IS NOT NULL in Where clause

### ISSUE THREAD

**Issue by TCB13** [fpdo/fluentpdo#107]
Hello,

I was reading the documentation and it's possible to do a `WHERE field IS NULL` with:

````
$table->where("field", null)	Translated to field IS NULL
````

However, I can't find any reference to a way to do a `IS NOT NULL`. If this is not currently possible I suggest an implementation like:

````
$table->where("field", !null)	Translated to field IS NOT NULL
````

We can detect when the there's a `!null` being passed as a parameter because in PHP if we do:
````
$parameter = !null;
if ($parameter === true)
	print "we've detected a NOT NULL!";
````
The condition evaluates as `true` and the string is printed. Live example here: http://sandbox.onlinephpfunctions.com/code/62a32c31c3ecf666747d81e58e8ad38487a12377

Thank you.

**Comment by odan** [comment]
Try this:

``
$table->where('field IS NOT ?', null)
``
