### ISSUE TITLE
Join

### ISSUE THREAD

**Issue by rorc** [fpdo/fluentpdo#108]
Need add other joins...
$fpdo->from('table')->leftOuterJoin();
$fpdo->from('table')->rightOuterJoin();
etc...

**Comment by rorc** [comment]
Now i use:
$sql = str_replace('INNER JOIN', 'LEFT OUTER JOIN', $this->getLinkedList()->getQuery(false));
$this->fdb->getPdo()->query($sql)->execute();

**Comment by cbornhoft** [comment]
These should be available through `CommonQuery::__call()`. They are documented at the top for IDEs to use but should work nonetheless.

**Comment by rorc** [comment]
Ok thanks!
