### ISSUE TITLE
OR condition

### ISSUE THREAD

**Issue by rorc** [fpdo/fluentpdo#113]
Now its very uncomfortably:
```php
$pdo->where('struct.name like ? or syn.name like ?' . ($showAddress ? ' or params.adres like ?' : ''), "%{$name}%", "%{$name}%", "%{$name}%");
```

Will be good this:

```php
$pdo->where('struct.name like ? or syn.name like ?', "%{$name}%", "%{$name}%");

if ($showAddress) {
    $pdo->whereOr('params.adres like ?', 1);
}
```

**Comment by rorc** [comment]
Why closed? :(

**Comment by rbellido** [comment]
I'd like to know why this was closed too. Here's a use case where a `whereOr` would be particularly useful:
```
->where("
                    A.id IN (
                        SELECT A.id
                        FROM A
                        WHERE A.another_field LIKE '%?%'
                    ) OR
                    C.id IN (
                        SELECT B.id
                        FROM B
                        WHERE B.some_field LIKE '%?%'
                    )
                ", $searchTerm);
        }
```

which gives me the following PDOException:
```
SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens
```

With a `whereOr` method, I can parametrize the different where clauses separately.

I don't know. Maybe there's a better way of achieving what I'm trying to do for my use. Regardless, it would still be nice to be able to do a `whereOr`.

**Comment by rbellido** [comment]
Ah, indeed. There is a better way of doing what I'm trying to achieve in my use case above: https://github.com/envms/fluentpdo/issues/188#issuecomment-262622496.
