### ISSUE TITLE
Joining on to a subquery

### ISSUE THREAD

**Issue by lewilewilewi** [fpdo/fluentpdo#116]
In this statement
`$query->innerJoin('(SELECT distinct a.col1 as col1
                                    FROM a
                                    INNER JOIN b ON a.id=b.id) AS subtable ON table.id = subtable.id);`
the resulting $query should have an string in $query->joins with value 'subtable'.  Instead, it has value 'distinct'.  This means that if you are doing the join multiple times with different subqueries, it doesn't add each join as it should do.

**Comment by cbornhoft** [comment]
This is too much of an edge-case to support. If you can provide a compelling reason to re-open, we will reconsider then.

**Comment by lewilewilewi** [comment]
It's valid SQL, and the current code handles it incorrectly.  Is that not compelling enough?

**Comment by cbornhoft** [comment]
If it's a simple fix on our part then it's no problem. However "It's valid SQL" does not mean it's worth supporting. Supporting every intricate query structure would mean an exponential increase in the size of Fluent's codebase. A line must be drawn somewhere. Another example: "DROP DATABASE employees;" is valid SQL, should we support that too? I realize it's different from what you're asking but it all ties into our main goal: Provide a clean, fast tool to build common queries. A complex query like this would be better suited for PDO itself in most cases.

Can you provide the final query string Fluent currently provides vs your expected result? We can go from there, and if it doesn't require much extra code, then we will consider.

**Comment by cbornhoft** [comment]
I've noted this for a future feature request.
