### ISSUE TITLE
Add REPLACE INTO support

### ISSUE THREAD

**Issue by gephaest** [fpdo/fluentpdo#121]
I was little confused when I hadn't found support for [*RELACE queries*] (https://dev.mysql.com/doc/refman/5.0/en/replace.html) with builder.

In my opinion FluentPDO may support all kinds of queries. This allows a developrers write more clean code without using `$dbh->getPdo()->exec()` statement.

**Comment by lichtner** [comment]
don't hesitate to send pull request

**Comment by gephaest** [comment]
Solved in #125 PR
