### ISSUE TITLE
Is there something like "fetchFlat" ?

### ISSUE THREAD

**Issue by dorian-marchal** [fpdo/fluentpdo#131]
Currently, I need a list of ids :

```php
$qb->from('article')->select(null)->select('id')->fetchAll();
```

Which returns :
```
$ids: {6} Array
(
 [0] => Array
     (
         [id] => 24
     )

 [1] => Array
     (
         [id] => 37
     )
     ...
)
```

I'd like something like that :

```
$ids: {6} Array
(
    [0] => 24
    [1] => 37
    ...
)
```

The closest workaround I found is `fetchPairs` :

```php
$ids = $qb->from('article')->select(null)->select('id')->fetchPairs('id', 'id');
```

Which returns :
```
$ids: {6} Array
(
    [24] => 24
    [37] => 37
    ...
)
```

Am I missing something ?

**Comment by jkufner** [comment]
When using plain [PDOStatement::fetchAll](http://php.net/manual/en/pdostatement.fetchall.php), you can do:

    ...->fetchAll(PDO::FETCH_COLUMN, 0);

**Comment by dorian-marchal** [comment]
Can I use `PDOStatement::fetchAll` with `FluentPDO` ?

**Comment by jkufner** [comment]
$ids = $qb->from('article')->select(null)->select('id')
        ->execute()->fetchAll(PDO::FETCH_COLUMN, 0);

I guess the BaseQuery::fetchAll should accept these parameters too (feature request detected).

**Comment by cbornhoft** [comment]
Closing, noted for future feature request.
