### ISSUE TITLE
Call Select without automatic Joinbuild

### ISSUE THREAD

**Issue by tyurderi** [fpdo/fluentpdo#132]
``` php
    $query = $fpdo->from('article')->select('user.name');
```

I think it would be great when I can pass a second param to this function which defines, that a left join should be created seperately or not.

Would be great :)

**Comment by jkufner** [comment]
Not really. This smart join feature is already extremely messy. It is much better to specify joins manually.

**Comment by tomew** [comment]
Yea but at this point I don't need a join because the way how the foregin-key is generated doesn't works for my table-structure and I do not seem to change it.

**Comment by bludream** [comment]
@tyurderi  could you show us your DB structure ?? I'm curious to see what made this great library not work

**Comment by cbornhoft** [comment]
Closing, noted for future feature request.
