### ISSUE TITLE
Support for Database Transactions

### ISSUE THREAD

**Issue by Jamesking56** [fpdo/fluentpdo#135]
Hey!

Great library! Its really awesome to work with on basic PHP projects.

One thing it is missing however is database transaction support. Is this possible to be able to build up a transaction and commit it when there are no errors.

I have a console script to import data into my database using your library and it loops over the data running an insert for each new record, it would be great to wrap this in a transaction incase it finds an error in the formatting of a certain record mid-way through.

Cheers and keep up the great work :+1:

**Comment by gephaest** [comment]
One possible way:
```php
$fpdo->getPdo()->exec('START TRANSACTION');
// do some queries
$fpdo->getPdo()->exec('COMMIT');
```

**Comment by maldoinc** [comment]
wrap your queries with the PDO native `beginTransaction`, `commit` and `rollback` after getting it's instance via `getPdo`

**Comment by jkufner** [comment]
Why not to add beginTransaction, commit and rollback to FluentPDO object as well? They would be very convenient shortcuts.

**Comment by yjimk** [comment]
For anyone else who comes across thisis an example of working code.

`$connection->beginTransaction();
// Any transactional update query, note the removal of ->execute()
$fpdo->update('users')->set($values)->where('id', $user_id); 
$connection->commit();`

Now that Google CloudSQL enforces GTID checks without the ability to turn it off, it will resolve the error message

PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1785 When @@GLOBAL.ENFORCE_GTID_CONSISTENCY = 1, updates to non-transactional tables can only be done in either autocommitted statements or single-statement transactions, and never in the same statement as updates to transactional tables.'
