### ISSUE TITLE
Prefix management

### ISSUE THREAD

**Issue by pascl** [fpdo/fluentpdo#138]
Hi,

Until now, I have left the smart join feature to generate my queries. My project is now bigger than I expected at the beginning and I added a prefix at each of my tables.

Here's a sample...
<code>$query = $fpdo
            ->from($db_prefix.'article')
            ->select($db_prefix.'user.name AS uname')
            ->where($db_prefix.'article.id', 1);</code>

My previous query (with empty prefix) was:
<code>SELECT article.*, user.name AS uname FROM article LEFT JOIN user ON user.id = article.user_id WHERE article.id = ?</code>

My new one (NOT empty prefix):
<code>SELECT prefix_article.*, prefix_user.name AS uname FROM prefix_article LEFT JOIN prefix_user ON prefix_user.id = prefix_article.prefix_user_id WHERE prefix_article.id = ?</code> 

The prefix is now added everywhere, also in field names and I did not expect that : field name in ON statement became **prefix_article.prefix_user_id** and not **prefix_article.user_id** that I expected.

Now, I have to modify the field name directly in my db (and again if I edit prefix). In order to avoid that, is there a simple way to manage a prefix only in table names ?

**Comment by cbornhoft** [comment]
Take a look at `FluentStructure.php`. In there is what specifies the default naming structure to use for both primary and foreign keys. You can change the directly, or pass your own `Structure` class into the `FluentPDO` constructor.
