### ISSUE TITLE
Lazy loading connection

### ISSUE THREAD

**Issue by Zyles** [fpdo/fluentpdo#140]
From my understanding, if we run this code:

```
$pdo = new PDO("mysql:dbname=fblog", "root");
$fpdo = new FluentPDO($pdo);
```

A connection is opened even if we do not run any queries. Is this correct?

Perhaps it would be better to only open the connection upon execute() etc.

I saw this at https://github.com/auraphp/Aura.Sql#lazy-connection-instance

**Comment by dgee2** [comment]
This may improve things for some use cases but there may be projects that
are using the DBMS user management for user authentication in which case
the presence of an active connection with their credentials would be all
that you would need to authenticate. @lichtner opinions?

**Comment by jkufner** [comment]
Lazy connections are good for a lot of use cases and bad for a lot of
usecases. It should be an option, it may be enabled by default.

**Comment by cbornhoft** [comment]
Closing, noted for future feature request.
