### ISSUE TITLE
 read and write

### ISSUE THREAD

**Issue by mlboy** [fpdo/fluentpdo#144]
add read and write separate？

**Comment by gephaest** [comment]
What?

**Comment by StefanYohansson** [comment]
@mlboy can you provide more info about this?

**Comment by maldoinc** [comment]
I think he asks if it's possible to have separate connections for read and write operations.

**Comment by cbornhoft** [comment]
FluentPDO simply accepts a PDO instance. This would be done by creating two PDO connections and passing them separately.

    $pdoRead  = new PDO($dsn, 'selectUser', 'password');
    $pdoWrite = new PDO($dsn, 'insertUpdateUser', 'password');

    $fpdoRead  = new FluentPDO($pdoRead);
    $fpdoWrite = new FluentPDO($pdoWrite);

Ensuring when and how to use each connection would be up to you. It would not make sense for us to determine that.
