### ISSUE TITLE
How do i handle fatal error "Too Many Connections"

### ISSUE THREAD

**Issue by harpreetsb** [fpdo/fluentpdo#145]
i sometimes get 
`
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [1040] Too many connections' 
`
i tried
```php
try{
			$this->pdo = new PDO("mysql:dbname=".$this->config->dbName, $this->config->dbUser, $this->config->dbPwd."d");
		}
		catch(Exception $ex){
			echo $ex->getMessage();
		}
```

but does not work.

**Comment by harpreetsb** [comment]
also does this library does not manage closing of db connections?

**Comment by StefanYohansson** [comment]
try this:

```
[...]
catch(PDOException $ex){
[...]
```

**Comment by cbornhoft** [comment]
Catching `PDOException` is the correct way to handle this.

As for connection management @harpreetsb, see issue [#157](https://github.com/fpdo/fluentpdo/issues/157)
