### ISSUE TITLE
Update query not using values

### ISSUE THREAD

**Issue by AlanOndra** [fpdo/fluentpdo#147]
Writing a query to activate a user based on a confirmation code:
```php
$query = $fluent->update($users)
	->leftJoin("`$confirm` ON `$confirm`.`userid` = `$users`.`id`")
	->set("`$users`.`active`",1)
	->where("`$confirm`.`key`",$key)
	->where("`$users`.`email`",$email);

var_dump($query->getQuery(true));
```
The result:
```
string(144) "UPDATE users
    LEFT JOIN `confirm` ON `confirm`.`userid` = `users`.`id` SET `users`.`active` = ?
WHERE `confirm`.`key`
    AND `users`.`email`"
```

Both `$email` and `$key` are correct before the query. If I use an array to pass in the values as a field:value pair it makes no difference.

**Comment by maldoinc** [comment]
It's due to the column names being backticked. Try removing that. We'll most likely address this very soon.

**Comment by maldoinc** [comment]
Hey @AlanOndra can you confirm this is resolved?

**Comment by maldoinc** [comment]
Marking this as resolved
