### ISSUE TITLE
How to create queries

### ISSUE THREAD

**Issue by PetarFedorovsky** [fpdo/fluentpdo#148]
How to create a query with :
WHERE ...
NOT IN, NOT LIKE, IS NULL, IS NOT NULL.

tnx,

**Comment by StefanYohansson** [comment]
IS NOT NULL and IS NULL:
```
$fpdo->where('active is not null');
$fpdo->where('active is null');
```

IN:
```
$fpdo->where('id', array(1, 3));
```

NOT IN and NOT LIKE isn't possible this way.

**Comment by cbornhoft** [comment]
@StefanYohansson Does

    $fpdo->from('table')->where('id NOT LIKE ?', [1, 3]);

not work as expected? I haven't tried reproducing this.

**Comment by StefanYohansson** [comment]
yeah, it works. My mistake.

**Comment by cbornhoft** [comment]
Awesome! Le closed.
