### ISSUE TITLE
Looking for new maintainer for FluentPDO

### ISSUE THREAD

**Issue by lichtner** [fpdo/fluentpdo#149]
Hi guys,
I am the creator of FluentPDO, but my activity for it has been very rare recently. To be honest more than 1 year ago I switched from php to nodejs. I don't expect use php any more. 

But I still believe that FluentPDO is a good library and it is worth to continue to be developed. There are some improvements and features waiting for implementation.

So I am looking for a new maintainer for FluentPDO. It could be a person or  some company. I prefer someone who wants to move it forward.

To the new maintainer I can move:
- github repo with more than 400 stars
- @fluentpdo twitter account
- domain fluentpdo.com

I have spent many hours with it in my free time. I prepared to pass it for free but financial consideration would be appreciated, but price is not most important criteria. FluentPDO is my child. At first I want to find someone who is able to develop it in a right way.

If you seriously want to be the maintainer, please contact me on my personal email marek.licht@gmail.com

**Comment by StefanYohansson** [comment]
Hi lichtner,
I emailed you about maintainer request. :)
