### ISSUE TITLE
FluentPDO\FluentPDO constructor with wrong PDO type

### ISSUE THREAD

**Issue by acceleraretur** [fpdo/fluentpdo#150]
PHP Version 5.6:
E_RECOVERABLE_ERROR : Argument 1 passed to FluentPDO\FluentPDO::__construct() must be an instance of FluentPDO\PDO, instance of PDO given

I updated 
function __construct(PDO $pdo, FluentStructure $structure = null) 
to 
function __construct(\PDO $pdo, FluentStructure $structure = null)

and fixed

**Comment by StefanYohansson** [comment]
can you send a PR for your solution? we'll review it.

**Comment by cbornhoft** [comment]
This most likely means you're namespacing FluentPDO by including it after another file with a declaration.

The fact that you need to escape to the global namespace gives it away.

**Comment by maldoinc** [comment]
Just close this IMO. We'll add namespacing sometime later on the project.
