### ISSUE TITLE
from() does not backtick table name

### ISSUE THREAD

**Issue by povilasb** [fpdo/fluentpdo#151]
This would not work:
```
$query = $fpdo->from("client-stats")
```
Because the table name "client-stats" is not bacticked. 
```
"`client-stats`" 
``` 
would work.

**Comment by maldoinc** [comment]
You can backtick it directly on the string. 

Eg. ```$query = $fpdo->from("`client-stats`")```

**Comment by povilasb** [comment]
If I have to do it often repeatedly, I consider it redundant.

**Comment by cbornhoft** [comment]
@povilasb FluentPDO would have to be aware of the driver in use in order to determine whether or not to backtick all table and column names. SQL Server for example, denotes these names using `[table]`.

**Comment by maldoinc** [comment]
I suppose that it's a valid request. However it's a breaking change so we
must further discuss this for future releases.
