### ISSUE TITLE
How to close connection?

### ISSUE THREAD

**Issue by cwramsey** [fpdo/fluentpdo#157]
I've looked through the methods but haven't found a way to close the connection to the database. What's the standard way to do that with fpdo? I'm running hundreds of queries pretty quickly and need to close the connections when I'm done.

**Comment by cbornhoft** [comment]
Using PDO there is no given method to close a database connection. The connection is active for the life of the object. Destroying the object and all references to it will close the connection.

    $fpdo = new FluentPDO($pdo);
    $query = $fpdo->from('table');
    foreach ($query as $row) {...}
    $pdo = $fpdo->getPdo() = null;
