### ISSUE TITLE
ODBC Driver does not support lastInsertId()

### ISSUE THREAD

**Issue by B1QB0SS** [fpdo/fluentpdo#164]
Hello i'm Using ODBC SQL Native Client 
i'm getting this error whenever i try to use InsertInto 

`Warning: PDO::lastInsertId(): SQLSTATE[IM001]: Driver does not support this function: driver does not support lastInsertId() in FluentPDO\InsertQuery.php on line 32`

Note: the query is executed and the row is inserted

**Comment by cbornhoft** [comment]
The PDO ODBC driver is a poor implementation and unfortunately doesn't support several methods that PDO offers.

This is a bug, but a bug with PDO. We can look into other ways to pull the last inserted id based on driver detection.

**Comment by B1QB0SS** [comment]
what about LIMIT Selection if you could implement it for SQL that would help 

Regards

**Comment by cbornhoft** [comment]
Are you saying `limit()` doesn't work with ODBC either?

**Comment by B1QB0SS** [comment]
no it doesn't work with ODBC because i use SQL Server there's no LIMIT we use TOP

**Comment by maldoinc** [comment]
Try connecting to MSSQL via `pdo_sqlsrv`, it's available here on github at [Azure/msphpsql](https://github.com/Azure/msphpsql) that should fix the `lastInsertId` call.

Also connecting to MSSQL via odbc has all sorts of problems for unicode strings, you're much better off via `pdo_sqlsrv`

**Comment by B1QB0SS** [comment]
thanks maldoinc i appreciate your advice i will try it
