### ISSUE TITLE
How to call a stored procedures

### ISSUE THREAD

**Issue by wipflash** [fpdo/fluentpdo#168]
Is there a way to call sp on fluent PDO?

**Comment by cbornhoft** [comment]
You should be able to use the `FluentPDO::getPdo()` method.

**Comment by wipflash** [comment]
Can you give me a example?
My SP with like bellow:
`sp_callDuty(':name', ':age', ':salary')`

**Comment by cbornhoft** [comment]
Assuming you're using MySQL, you can call it using:

    $fpdo->getPdo("CALL sp_callDuty(':name', ':age', ':salary')");

**Comment by ingjuanmanuelrivera** [comment]
Hi, i try to use it this method $fpdo->getPdo("CALL MyProcedure('1')");  but this operation don't work.

i write also with mistakes but the getPdo don't execute nothing, what need to write in my code ? 

thanks

**Comment by cbornhoft** [comment]
Hmm I'm not sure why I wrote it like that. `getPdo()` returns the instance of PDO so that code would be wrong. In your case you'd use:

    $fpdo->getPdo()->query("CALL myProcedure('1')");

**Comment by dpp92** [comment]
> 
[asdasdsadasd](asdasdasdasdasdasdaasdasdasdasdasdasda)
> dasasdasdasdasdasd

> dasdsadsadasdasd

> 

>
