### ISSUE TITLE
Only one tagged release... which is over a year old

### ISSUE THREAD

**Issue by magnus-eriksson** [fpdo/fluentpdo#171]
Will there be any new tags for this project, or are we stuck on 1.0.0 when we're using Composer? I can see on the master branch that here have been a bunch of development since that version.

I never use dev-master in my projects. I need to know that I get the same version of a package the next time I set up the project/install dependencies and won't get any breaking changes.

I really like this package. I just wish I could use it. :(

**Comment by cbornhoft** [comment]
Any development with this version only includes non-breaking changes, so you should be able to use master without losing much sleep. Version releases are in the works, however everyone is pretty swamped with other projects.

I will be releasing a new tagged version with bug fixes etc within the coming month (latest July 1st). You can hold me to that!

**Comment by magnus-eriksson** [comment]
:+1: Fair enough!

I'll just use dev-master until then. Cheers! :)

**Comment by jkufner** [comment]
Please keep in mind, that tools like Composer use by default only tagged
versions. So if the last tag is year old, it means nobody uses patches
published for the last year.

There is nothing wrong with simply incrementing minor number iof the
version string and releasing a bug fix release with minimal comment. If
master is stable enough to use, it should be barely noticable amount of
work to do.


Chris Bornhoft wrote, on 26.5.2016 19:30:

**Comment by magnus-eriksson** [comment]
This feels like déjà vu: https://github.com/fpdo/fluentpdo/issues/87

**Comment by dmitry-varennikov-eventbase** [comment]
> I will be releasing a new tagged version with bug fixes etc within the coming month (latest July 1st). You can hold me to that!

Looking forward to it but meanwhile I can't depend on `dev-master` which means I can't use your library. This is sad!

**Comment by cbornhoft** [comment]
v1.1 released!
