### ISSUE TITLE
UNION statements

### ISSUE THREAD

**Issue by beaudesigns** [fpdo/fluentpdo#27]
I have a case where I need to UNION 2 queries.

    SELECT * FROM tableOne WHERE name = 'bob'
    UNION
    SELECT * FROM tableTwo WHERE name = 'bob'

I'm trying to figure out what the syntax should be if I were to build this into FluentPDO. My first thought is to build 2 fluent PDO objects, then on one of them, be able to call `->union()`

    $tableTwoFluent = $fluent->from('tableTwo')->where('name', 'bob');
    $tableOneFluent = $fluent->from('tableOne')->where('name', 'bob')->union($tableTwoFluent);

What are your thoughts?

**Comment by cbornhoft** [comment]
This won't be too difficult to implement, but we are closing this for a new release.
