### ISSUE TITLE
Problem with insert

### ISSUE THREAD

**Issue by victorhqc** [fpdo/fluentpdo#49]
I have this table
```
CREATE TABLE IF NOT EXISTS `login` (
  `idLogin` bigint(20) NOT NULL AUTO_INCREMENT,
  `idUser` bigint(20) NOT NULL,
  `date` datetime NOT NULL,
  `expiracy` datetime NOT NULL,
  `key` varchar(255) NOT NULL,
  `active` tinyint(1) NOT NULL DEFAULT 1,
  `ip` varchar(30) NULL,
  `os` varchar(30) NULL,
  `screen_resolution` varchar(30) NULL,
  PRIMARY KEY (`idLogin`),
  KEY `idUser` (`idUser`),
  UNIQUE KEY `key` (`key`),
  CONSTRAINT `login_idUser` FOREIGN KEY (`idUser`) REFERENCES `users` (`idUser`) ON DELETE CASCADE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

```
The problem is how the query is created, and I don't know if this bug is because fluentpdo or PHP pdo.

When I do this:
```
$query = $this->_fdb->insertInto('login')->values($data);
die($query->getQuery());
```
I get this response:
```
INSERT INTO login (idUser, date, expiracy, key, active)
VALUES ('1', '2013-11-13 21:18:51', '2013-12-11 21:18:51', 'QMgwJOAy]s0pVt2W/LlFnYUfmx8T&cDBr3[}CG@b{;jXI6zRi57.E4$vq,!S', 1)
```

The table columns should be like `( \`idUser\`, \`date\`, \`expiracy\`, \`key\`, \`active\`)` because key is a restricted MySQL Word

**Comment by cbornhoft** [comment]
Feature request to be returned to later. (Add escape mechanism based on detected dbms)

**Comment by yogeshpatel2200** [comment]
Hello i have 3 insertquery in pdo, when i execute 1st query then i got primary key or last insert id,but when i execute 2nd query i can not get primary key or last insert id. Please help me out this problem.
