### ISSUE TITLE
Get Error Code and Error Message separately

### ISSUE THREAD

**Issue by evandroabukamel** [fpdo/fluentpdo#61]
I produced a SQL error and setting up the debug I get que following message:

Warning: PDOStatement::execute(): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tbinterveniente.id_dados' in 'where clause' in /www/usuario/evandro/system/lichtner-fluentpdo/FluentPDO/BaseQuery.php on line 117

Now, how can I get the error code (SQLSTATE[42S22]) and the rest of the message separately?

Thanks.

**Comment by badpenguin** [comment]
It does not work, we need to capture error in execute() method since the
result is being returned as FALSE to the calling app.

I think we need to "PDOStatement::errorInfo ( void )" inside fluentPDO and cache it as properties.

**Comment by badpenguin** [comment]
in BaseQuery.php at line 291 before $result=FALSE; just capture the statement error.

is that ok?

**Comment by badpenguin** [comment]
ok 2 approaches:

1) we can preserve the result so getResult() will return it and errorInfo() will work outside of FluentPDO namespace:

'''
		$time = microtime(true);
		if ($result && $result->execute($parameters)) {
			$this->time = microtime(true) - $time;
			$result2 = $result;
		} else {
			$result2 = false;
		}

		$this->result = $result;
		$this->debugger();

		return $result2;
'''

2)
or, before 
'''
$result = false;
'''

we add

'''
$this->errorInfo = $result->errorInfo();
'''
and a public getErrorInfo() method.

**Comment by badpenguin** [comment]
@lichtner please let me know your opinion so i can patch the source according to it :)

**Comment by kimsyversen** [comment]
+1 :)
