### ISSUE TITLE
Namespaces?

### ISSUE THREAD

**Issue by neoascetic** [fpdo/fluentpdo#86]
Or this is for compatibility? I am not sure if anyone still seat on `PHP < 5.3` and lower :)

There already is [fork](https://github.com/okonomi/fluentpdo/tree/modernize) with required changes so you could simply merge that branch to the master. With reverting changes of short array construction syntax for 5.3 branch support (which is already unsupported, though).

**Comment by TCB13** [comment]
+1 on this. There are a few forks including namespaces on this. ;)

**Comment by alexantr** [comment]
And PSR-1 Coding Standard will be :+1:

**Comment by odan** [comment]
Hey it's 2016. Namespaces and PSR-2 coding style would be great :+1:

**Comment by cbornhoft** [comment]
This will be implemented in our upcoming version. Legacy will keep the current format.
