### ISSUE TITLE
Empty IN statements

### ISSUE THREAD

**Issue by rr-** [fpdo/fluentpdo#88]
Some DB drivers, for example - MySQL, will show errors when trying to use statements like these:

    $query = $fpdo->from('posts')->where('id', []);
    echo $query->getQuery();
    iterator_to_array($query);

---

     SELECT posts.* FROM posts WHERE id IN ()

---

    SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1

**Comment by cbornhoft** [comment]
Closing, noted for future feature request.
