### ISSUE TITLE
PDO::FETCH_CLASS constructor arguments

### ISSUE THREAD

**Issue by basert** [fpdo/fluentpdo#91]
Hey guys,

fiddled around with this tonight and I'm pretty amazed that everything works that well with my custom php framework!

But found one thing: Is it possible to alter the execute call in [BaseQuery.php ](https://github.com/lichtner/fluentpdo/blob/master/FluentPDO/BaseQuery.php) line 108 to add an constructor argument?

```php
if (class_exists($this->object)) {
	$result->setFetchMode(PDO::FETCH_CLASS, $this->object, array(true));
} else {
	$result->setFetchMode(PDO::FETCH_OBJ);
}
```
Because I'm checking in my constructor, if the object is taken from database or initialized by a User.

**Comment by cbornhoft** [comment]
Closing, noted for future feature request.
